name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup
      run: make setup

    - name: Execute tests
      run: make test

    - name: Run linter
      run: make lint
